import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import { useState } from 'react';
import { Header } from './components/header';

export default function Home() {

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const router = useRouter();
  const routeToDoctorize = () => {
    router.push('/doctorize');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Nav */}
      <div>
        <Header />
      </div>

      {/* Body */}
      <div>
        <h1>Login</h1>
        <form>
          <input type="text" value={username} name="username" placeholder="Username" onChange={e => setUsername(username)} />
          <input type="password" value={password} name="password" placeholder="Password" onChange={e => setPassword(password)} />
          <button type="button" onClick={routeToDoctorize}>Login</button>
        </form>
        <button className={styles.button} onClick={routeToDoctorize}>Doctorize</button>
      </div>
    </div>
  )
}
