import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';

export default function Home() {

  const routeToDoctorize = () => {
    const router = useRouter();
    router.push('/doctorize');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Welcome to Doctorize.AI</h1>
        <button className={styles.button} onClick={routeToDoctorize}>Doctorize</button>
      </div>
    </div>
  )
}
