import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import { useState } from 'react';
import { Header } from './components/header';

export default function Home() {

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const router = useRouter();
  const routeToDoctorize = () => {
    router.push('/doctorize');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Doctorize.AI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Nav */}
      <div>
        <Header />
      </div>

      {/* Body */}
      <div className={styles['login-container']}>
        <h1>Log In</h1>
        <form>
          <div className={styles['input-container']}>
            <input className={styles.input} type="text" value={username} name="username" placeholder="Email" onChange={e => setUsername(e.target.value)} />
            <input className={styles.input} type="password" value={password} name="password" placeholder="Password" onChange={e => setPassword(e.target.value)} />
            <button className={`${styles.button} ${styles.red}`} type="button" onClick={routeToDoctorize}>Log In</button>
          </div>
        </form>
      </div>
    </div>
  )
}
